apiVersion: openapi/v2
kind: Service
metadata:
  name: devops-capstone-lb
  labels:
    app: devops-capstone
spec:
  type: LoadBalancer
  selector:
    app: devops-capstone
  ports:
    - port: 80
      targetPort: 80