---
    - hosts: 127.0.0.1
      connection: local
      vars:
        download_dir: "{{ lookup('env', 'HOME') }}"
        kubernetes_version: "1.14"
      become: yes
      tasks:
        # ensure that only one cluster exists at a time
        - name: Get existing cluster
          command: eksctl get clusters
          register: existing_clusters
          become: no
        - debug: msg=" {{ existing_clusters.stdout }}"
        - name: Setup K8s-cluster with eksctl
          block:
            - name: Setup clusters on 4 nodes
              command: >
                eksctl create cluster
                --name test-cluster
                --version {{ kubernetes_version }}
                --region us-east-1
                --nodegroup-name workers-node
                --node-type t2.micro
                --nodes 2
                --nodes-min 1
                --nodes-max 3
                --managed
              become: no
            - name: Update kubeconfig
              command: aws eks --region us-east-1 update-kubeconfig --name test-cluster
          when: "existing_clusters.stdout.find('No clusters found') != -1"